name: 'build'

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  MCUboot:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        targets: [esp32c3]
    steps:
      - uses: actions/checkout@v3
      - name: Build MCUboot bootloader
        uses: docker://docker.io/espressif/idf:v5.3
        with:
          args: /bin/sh -c "git config --global --add safe.directory '*' && cd mcuboot && git am ../esp32c3.diff && cd .. && ./build_mcuboot.sh -s -c ${{matrix.targets}}"
      - uses: actions/upload-artifact@v3
        with:
          name: mcuboot-builds
          path: out/

  Release-Artifacts:
    runs-on: ubuntu-20.04
    needs: [MCUboot]
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          path: buildartifacts/
      - name: Update release
        if: "github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags/')"
        uses: pyTooling/Actions/releaser@r0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          files: |
            buildartifacts/mcuboot-builds/*
          tag: latest
          rm: true
